data_file = /home/cdkbs/bench-runs/az-s7b/c1-n1000-run1/B/kds.db
cores = 1
port = 15600
durability = relaxed
log_dir = /home/cdkbs/bench-runs/az-s7b/c1-n1000-run1/B
log_file = kds.log
log_level = warn
